config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'quotes/random' => 'quotes#random'
  resources :quotes
  root 'quotes#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
	validates :author,	presence: true,
						length: {minimum: 1}
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/tags2quote.rb
class Tags2quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	def index
		# @quotes = Quote.all
		@tags = Tag.all
		@jonction = Tags2quote.all
		@quotes = []
		Quote.all.each_index do |i|
			@quotes[i] = QuoteTags.new
			@quotes[i].id = Quote.all[i].id
			@quotes[i].author = Quote.all[i].author
			@quotes[i].text = Quote.all[i].text
			@quotes[i].tags = getTags(@quotes[i].id, @jonction, @tags)
		end

	end	

	def show
		@quote = Quote.find(params[:id])
	end

	def new
		@quote = Quote.new
	end
	
	def edit
		@quote = Quote.find(params[:id])
	end
	def update
		@quote = Quote.find(params[:id])
		
		if @quote.update(quote_params)
			redirect_to quotes_path
		else
			render 'edit'
		end
	end

	def create
		@params 	= 	quote_params
		@tagsTab 	= 	@params["tags"].split(' ')

		# Create Quote
		@quote = Quote.new
		@quote.author 	= 	@params["author"]
		@quote.text 	= 	@params["text"]
		@quote.save
		@quoteId = Quote.last.id

		if @tagsTab.length != 0 then
			@tagsTab.each do |newTag|
				#Create Tag
				@tags 	= Tag.all.where("name = '#{newTag}'")
				if @tags.length == 0 
					@tag = Tag.new
					@tag["name"] 	= 	newTag
					@tag.save
				end
				@tagId = Tag.all.where("name =  '#{newTag}'")[0].id

				#Create Association
				@tag2quote 	= Tags2quote.new
				@tag2quote.tag_id = @tagId
				@tag2quote.quote_id = @quoteId
				@tag2quote.save
			end
		end

		#redirect_to @quote
		if @quote.save
			@tags = Tag.all
			@jonction = Tags2quote.all
			
			@tab = []
			@send = QuoteTags.new
			@send.id = Quote.last.id
			@send.author = @quote.author
			@send.text = @quote.text
			@send.tags = getTags(@send.id, @jonction, @tags)
			
			@tab.push(@send)
			@tab.push(Tag.all)
			@tab.push(Tags2quote.all)

			render json: @tab
		else
			render json: @quote.errors, status: :unprocessable_entity
        end
	end
	
	def destroy
		id = params[:id]
		@quote = Quote.find(id)
		@quote.destroy

		#Remove Association
		@jonction = Tags2quote.where(quote_id: id)
		if @jonction != nil
			@jonction.each do |e|
				tagId = e.tag_id
				e.destroy
				
				tagNumber = 0
				Tags2quote.all.each do |tag|
					if tag.tag_id == tagId
						tagNumber += 1
					end
				end
				if tagNumber === 0
					Tag.find(tagId).destroy
				end
			end
		end
		

		#Remove null tags
		@tab = []
		@tab.push(Tag.all)
		@tab.push(Tags2quote.all)

		render json: @tab
        
		
	end
	
	def random
		@random = Quote.all[rand(Quote.all.length)]
		redirect_to quote_path(@random.id)
	end

	private
		def quote_params
			params.require(:quote).permit(:author, :text, :tags)
		end

		def getTags(id, tags, tagsName)
			tagsTab = []
			tags.each do |tag|
				if tag.quote_id == id
					tagsTab.push(tagsName.find(tag.tag_id).name)
				end
			end
			return tagsTab
		end

		class QuoteTags
			attr_accessor :id, :author, :text, :tags
			def initialize
				@id, @author, @text, @tags = ""
			end 
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comments</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag 'masonry', :media => 'screen' %>
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for @quote do |f| %>
 
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@quote.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @quote.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row"> 
  <div class="input-field col s12">
    <%= f.text_field :author, :class => "validate" %>
    <%= f.label :author, :class => 'active' %><br>
  </div>
 </div>
<div class="row">
  <div class="input-field col s12">
    <%= f.text_area :text, :class => "materialize-textarea" %>
    <%= f.label :text, :class => 'active' %><br>
  </div>
</div>
<div class="row">
	<div class="col s1 offset-s10">
		<%= f.submit  raw("Send"), :class => "btn waves-effect waves-light"  %>
	</div>
</div>
 
<% end %>

app/views/quotes/_nav.html.erb
<nav>
	<div class="nav-wrapper blue">
		<%= link_to params, "/#", :class => 'brand-logo' %>
		 <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
		<ul class="right hide-on-med-and-down">
			<li><%= link_to 'Home', root_path %></li>
			<li><%= link_to 'New Quote', new_quote_path %></li>
			<li><%= link_to 'Random Quote', quotes_random_path %></li>
		</ul>
		<ul class="side-nav" id="mobile-demo">
			<li><%= link_to 'Home', root_path %></li>
			<li><%= link_to 'New Quote', new_quote_path %></li>
			<li><%= link_to 'Random Quote', quotes_random_path %></li>
		</ul>
	</div>
</nav>

app/views/quotes/edit.html.erb
<%= render 'nav', params: "Edit Quote" %>
<%= render 'form' %> 

app/views/quotes/index.html.erb
<%= render 'nav', params: "Listing Quotes" %>
<%= react_component('Quotes', {data: @quotes, tags: @tags, jonction: @jonction})%>

app/views/quotes/new.html.erb
<%= render 'nav', params: "New Quote" %>
<%= render 'form' %>

app/views/quotes/show.html.erb
<%= render 'nav', params: "Quote" %>
<div class="row">
	<div class="col s12 m3">
		<div class="card">
		<div class="card-content">
			<span class="card-title"> <%= @quote.author %> </span>
			<p> <%= @quote.text %> </p>
		</div>
		<div class="card-action">
			<%= link_to 'Edit', edit_quote_path(@quote) %>
			<%= link_to 'Delete', quote_path(@quote),
									method: :delete %>
		</div>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<%= react_component('Quotes', {data: @quotes}) %>